### ISSUE TITLE
SQL Syntax error on traffic update (dummy)

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-block#48]
With the current master using the blockserver in dummy mode, I get the following exception:
```
 Uncaught exception GET /api/v0/files/b179fc5d-7b35-431e-aee5-c380cce83d19/dffb9318-3018-4c5b-8f62-6d3bfcd91883 (10.0.2.2)
    HTTPServerRequest(protocol='http', host='localhost:9697', method='GET', uri='/api/v0/files/b179fc5d-7b35-431e-aee5-c380cce83d19/dffb9318-3018-4c5b-8f62-6d3bfcd91883', version='HTTP/1.1', remote_ip='10.0.2.2', headers={'Connection': 'Keep-Alive', 'Host': 'localhost:9697', 'Authorization': 'Token 3a3ff62e356864158add688b705eba708baebc37', 'User-Agent': 'Apache-HttpClient/4.5.2 (Java/1.8.0_91)'})
    Traceback (most recent call last):
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/vagrant/qabel-block/src/blockserver/server.py", line 193, in get
        yield self.save_traffic_log(prefix, size)
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/vagrant/qabel-block/venv_5264491bb3106619e03c80cba8193ddc0047dc87/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "<string>", line 6, in _wrap_awaitable
      File "/vagrant/qabel-block/src/blockserver/server.py", line 254, in save_traffic_log
        (await self.get_database()).update_traffic(prefix, traffic)
      File "/vagrant/qabel-block/src/blockserver/backend/database.py", line 120, in update_traffic
        (amount, util.this_month(), prefix))
    psycopg2.ProgrammingError: syntax error at or near "ON"
    LINE 1: ...ERE name = 'b179fc5d-7b35-431e-aee5-c380cce83d19' ON CONFLIC...
                                                                 ^
```

If the dummy mode doesn't use postgres it's obvious, but I don't know if thats true.
Started with:
```BASH
python run.py --debug --dummy --dummy-log --dummy-cache --apisecret=Changeme --accounting-host=http://localhost:9696 --address=0.0.0.0 --port=9697 --psql-dsn='postgres://block_dummy:qabel_test_dummy@localhost/block_dummy'
```

Pretty important because both, the desktop-client and the qabel-core use the blockserver this way for their integration tests.

**edit: wait, using postgres 9.4 .. fixing...**

**Comment by julianseeger** [comment]
me culpa
